### ISSUE TITLE
ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process

### ISSUE THREAD

**Issue by marian100521** [el3um4s/memento-svelte-electron-typescript#2]
Hi!
I've found your awesome project and I'd like to work with it, but after running `npm start`, and the `npm run nodemon`, I'm having the next error message: 

`ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process`
```

System Information: 
Kubuntu 20.04
OS-TYPE; 64 byte
Node version: 14.18.1
Npm version: 6.14.15
```

After reading some documentation I've uninstalled Google Chrome from my SO, but still the same.

Thanks in advance.

**Comment by el3um4s** [comment]
Hello :)

I'm not testing this repository on Linux. I just uploaded a new version with updated Electron and Nodemon. You can try if it works.

Alternatively you can try changing the startup script by adding some arguments:

```json
"scripts": {
  // ...
  "start": "npm run compile && electron --disable-gpu --disable-software-rasterizer .",
  "start:svelte": "rollup -c & npm run compile && electron --disable-gpu --disable-software-rasterizer  .",
  // ...
}
```

You can also try to edit the `src/electron/index.ts` file by adding these lines befdore `app.on("ready"...)`:

```ts
app.commandLine.appendSwitch('disable-gpu');
app.commandLine.appendArgument('disable-gpu');
```

Let me know if it works

**Comment by marian100521** [comment]
Sorry for the delay!
Yes, it fixed my issue.

> Hello :)
> 
> I'm not testing this repository on Linux. I just uploaded a new version with updated Electron and Nodemon. You can try if it works.
> 
> Alternatively you can try changing the startup script by adding some arguments:
> 
> ```json
> "scripts": {
>   // ...
>   "start": "npm run compile && electron --disable-gpu --disable-software-rasterizer .",
>   "start:svelte": "rollup -c & npm run compile && electron --disable-gpu --disable-software-rasterizer  .",
>   // ...
> }
> ```
> 
> You can also try to edit the `src/electron/index.ts` file by adding these lines befdore `app.on("ready"...)`:
> 
> ```ts
> app.commandLine.appendSwitch('disable-gpu');
> app.commandLine.appendArgument('disable-gpu');
> ```
> 
> Let me know if it works
